In [3]:
import pandas as pd
import numpy as np

In [18]:
df1 = pd.read_csv('gene_counts1.csv')
df2 = pd.read_csv('gene_counts2.csv')
df3 = pd.read_csv('gene_counts3.csv')

In [5]:
df1

,target_id,SRR3438884,SRR3438860,SRR3438634,SRR3438649,SRR3438578,SRR3438825,SRR3438792,SRR3438695,SRR3438897,...,SRR3438684,SRR3438783,SRR3438834,SRR3438569,SRR3438636,SRR3438731,SRR3438886,SRR3438862,SRR3438673,SRR3438774
0,NM_000014.6,9058.240000,19558.0000,3328.23000,1739.090000,4072.87000,9081.11000,9347.3500,8327.06000,7973.81000,...,6907.3600,10151.3000,1578.61000,3086.3700,3775.9700,6206.7900,8083.0400,5675.5500,3751.03000,4458.0200
1,NM_000015.3,1.000000,5.0000,0.00000,2.000000,0.00000,3.00000,6.0000,3.00000,3.00000,...,0.0000,6.0000,5.00000,1.0000,7.0000,1.0000,2.0000,4.0000,0.00000,0.0000
2,NM_000016.6,765.392000,1210.3300,335.88200,474.158000,387.59600,775.48000,901.0050,951.87100,947.30800,...,531.4000,936.2740,1119.40000,336.6030,381.8850,198.3610,562.4010,1221.6200,292.75400,485.8950
3,NM_000017.4,247.395000,429.0790,291.21600,639.612000,64.37940,342.12300,526.1810,379.51300,372.88600,...,242.0540,542.6150,545.39400,202.1490,580.6260,215.5560,192.3140,655.6620,425.41400,548.3110
4,NM_000018.4,3853.260000,5505.7000,2998.97000,3269.560000,1915.14000,6124.94000,5311.2200,4817.64000,3997.79000,...,3327.6500,6102.5900,6422.55000,3502.2900,2631.6300,1798.1000,3490.8000,5283.8400,3127.47000,4583.0400
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78746,NR_170930.1,0.000000,0.0000,0.00000,0.000000,0.00000,0.00000,16.9050,0.00000,46.89300,...,42.5876,0.0000,9.37873,0.0000,19.2081,37.8582,29.2643,15.3945,0.00000,0.0000
78747,NR_170931.1,0.167116,0.0000,24.03430,55.899300,3.80102,23.02010,0.0000,6.97707,1.02534,...,18.2124,25.9238,63.54850,27.5974,23.9782,10.9788,25.5562,25.4710,0.00000,96.6875
78748,NR_170932.1,71.403100,99.5886,30.20180,38.249200,28.99370,70.00940,73.7652,105.84800,106.53600,...,28.0431,81.6857,109.94400,50.3289,30.4050,221.6690,69.8579,124.1300,28.88790,193.1140
78749,NR_170933.1,8.122410,41.3945,6.67573,17.916100,6.60821,5.92063,20.5814,20.10450,12.89330,...,21.8744,21.9587,37.13830,7.8071,13.9446,20.1698,18.1924,18.3109,8.18972,36.5067
78750,NR_170934.1,2.505970,11.5898,0.00000,0.000023,5.18731,0.00000,0.0000,0.00000,0.00000,...,0.0000,0.0000,0.00000,0.0000,0.0000,0.0000,0.0000,0.0000,4.05917,0.0000

In [6]:
df2

,target_id,SRR3438757,SRR3438873,SRR3438879,SRR3438686,SRR3438615,SRR3438781,SRR3438561,SRR3438739,SRR3438733,...,SRR3438697,SRR3438703,SRR3438901,SRR3438895,SRR3438625,SRR3438843,SRR3438587,SRR3438849,SRR3438767,SRR3438660
0,NM_000014.6,9806.3600,9335.06000,4218.24000,0.0,2440.26000,4481.60000,4137.700000,1.503320e+04,9.520620e+03,...,5213.98000,10348.700000,9033.13000,2612.380000,2508.91000,14584.600000,3762.22000,10234.300000,2941.790000,4586.85000
1,NM_000015.3,7.0000,1.00000,2.00000,0.0,6.00000,5.00000,6.000000,1.500000e+01,2.000000e+00,...,5.00000,6.000000,6.00000,0.000000,5.00000,5.000000,1.00000,3.000000,4.000000,0.00000
2,NM_000016.6,894.8050,162.18800,299.54200,0.0,474.58900,926.60600,711.466000,1.067050e+03,6.456180e+02,...,532.58000,1109.540000,701.72600,589.376000,508.67000,1269.940000,268.90200,1067.690000,717.133000,277.14500
3,NM_000017.4,502.4220,130.59900,228.57800,0.0,402.76400,724.16000,444.654000,1.030810e+03,3.187500e+02,...,335.48400,646.223000,560.79400,211.089000,341.52300,386.641000,269.39500,533.080000,372.867000,365.37900
4,NM_000018.4,7224.0800,1361.32000,3213.08000,0.0,2506.49000,6502.15000,4436.420000,6.755740e+03,4.194480e+03,...,2765.48000,6570.470000,3635.83000,2885.750000,2436.57000,5390.130000,2202.21000,6479.720000,6526.180000,3011.19000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78746,NR_170930.1,0.0000,0.00000,16.40860,0.0,17.30290,0.00000,0.000000,2.185530e+01,4.082390e-08,...,0.00000,0.000000,0.00000,0.099777,8.83390,32.841700,0.00000,26.681000,30.262800,8.78056
78747,NR_170931.1,76.9842,61.11560,16.93400,0.0,13.84790,102.91600,0.000022,0.000000e+00,8.367040e+00,...,20.12920,0.176304,75.76750,30.060900,16.49570,42.330300,11.46400,0.002339,0.000027,33.01720
78748,NR_170932.1,200.4920,196.62700,54.01510,0.0,35.16070,104.63600,92.229900,7.413570e+01,1.067620e+02,...,45.54030,75.470300,170.30800,106.618000,19.34670,73.031000,18.20920,138.547000,77.840800,52.78500
78749,NR_170933.1,29.4954,9.47536,7.43167,0.0,5.88532,18.82450,24.753900,3.498750e+01,2.482420e+01,...,12.40010,40.630900,8.31975,22.719000,3.90419,34.816900,5.90468,28.815100,30.756200,13.74240
78750,NR_170934.1,0.0000,0.00000,0.00000,0.0,0.00000,6.72186,0.000000,7.542870e-08,1.031770e+01,...,1.76533,0.000000,3.84511,0.000000,0.00000,0.000002,0.00000,9.934240,0.000000,0.00000

In [7]:
df3

,target_id,SRR3438904,SRR3438803,SRR3438768,SRR3438612,SRR3438582,SRR3438846,SRR3438743,SRR3438644,SRR3438810,...,SRR3438779,SRR3438906,SRR3438655,SRR3438752,SRR3438628,SRR3438839,SRR3438564,SRR3438689,SRR3438610,SRR3438717
0,NM_000014.6,5149.85000,6146.9300,2.046910e+04,5090.4300,3635.18000,7625.520000,8521.1200,1455.57000,15456.7000,...,15217.200000,7119.44000,1036.59000,17038.5000,3143.94000,5604.12000,4306.16000,0.0,2840.83000,13565.60000
1,NM_000015.3,2.00000,5.0000,4.000000e+00,1.0000,2.00000,5.000000,5.0000,5.00000,8.0000,...,11.563100,0.00000,0.00000,5.0000,0.00000,7.00000,0.00000,0.0,0.00000,5.00000
2,NM_000016.6,86.36900,1164.3800,8.590810e+02,314.9460,374.30500,1358.570000,914.4110,270.02700,1762.6500,...,1509.450000,1127.20000,234.61300,1115.6700,390.04800,583.11700,371.35900,0.0,314.50900,1235.26000
3,NM_000017.4,237.29200,652.1350,9.980580e+02,87.6826,204.00000,403.922000,255.3150,458.46000,777.0050,...,919.191000,72.05450,276.34200,638.6920,298.21500,336.76800,169.93700,0.0,147.69600,291.32300
4,NM_000018.4,1651.36000,7886.8400,8.704770e+03,2094.9500,2002.73000,5572.870000,3675.5000,2310.00000,7847.1700,...,8474.290000,1986.51000,2062.04000,6458.4100,2830.43000,5175.77000,2632.81000,0.0,1836.96000,4345.36000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78746,NR_170930.1,0.00000,0.0000,0.000000e+00,0.0000,0.00000,0.361173,0.0000,0.00000,0.0000,...,77.327200,21.21770,30.06150,84.6140,32.94070,0.00000,0.00000,0.0,0.00000,0.00000
78747,NR_170931.1,132.19800,53.5833,6.120880e-08,14.1995,3.41431,36.004700,22.7983,0.00000,68.9534,...,0.012251,3.41303,0.00000,62.8400,0.06845,8.14061,0.00000,0.0,16.39390,7.70551
78748,NR_170932.1,331.24100,187.4880,7.542080e+01,24.1990,16.48080,91.994200,106.0700,42.47860,96.2081,...,108.979000,43.69110,41.53030,148.1830,38.38150,75.81180,42.89750,0.0,19.43150,79.12870
78749,NR_170933.1,9.58648,30.2987,2.394820e+01,3.3908,7.84120,28.814900,26.4489,1.98327,31.5990,...,36.739600,21.92300,7.84653,36.5171,13.90870,14.68530,9.65578,0.0,2.22746,33.07580
78750,NR_170934.1,0.00000,0.0000,0.000000e+00,0.0000,0.00000,1.572750,0.0000,0.00000,8.3640,...,0.000000,0.00000,0.00000,0.0000,0.00000,0.00000,0.00000,0.0,7.72891,0.00000

In [30]:
df = pd.concat([df1,df2,df3],axis=1)

In [31]:
df = df.loc[:,~df.columns.duplicated()]

In [35]:
df.to_csv('gene_counts.csv',index=False)

In [36]:
pd.read_csv('gene_counts.csv')

,target_id,SRR3438884,SRR3438860,SRR3438634,SRR3438649,SRR3438578,SRR3438825,SRR3438792,SRR3438695,SRR3438897,...,SRR3438779,SRR3438906,SRR3438655,SRR3438752,SRR3438628,SRR3438839,SRR3438564,SRR3438689,SRR3438610,SRR3438717
0,NM_000014.6,9058.240000,19558.0000,3328.23000,1739.090000,4072.87000,9081.11000,9347.3500,8327.06000,7973.81000,...,15217.200000,7119.44000,1036.59000,17038.5000,3143.94000,5604.12000,4306.16000,0.0,2840.83000,13565.60000
1,NM_000015.3,1.000000,5.0000,0.00000,2.000000,0.00000,3.00000,6.0000,3.00000,3.00000,...,11.563100,0.00000,0.00000,5.0000,0.00000,7.00000,0.00000,0.0,0.00000,5.00000
2,NM_000016.6,765.392000,1210.3300,335.88200,474.158000,387.59600,775.48000,901.0050,951.87100,947.30800,...,1509.450000,1127.20000,234.61300,1115.6700,390.04800,583.11700,371.35900,0.0,314.50900,1235.26000
3,NM_000017.4,247.395000,429.0790,291.21600,639.612000,64.37940,342.12300,526.1810,379.51300,372.88600,...,919.191000,72.05450,276.34200,638.6920,298.21500,336.76800,169.93700,0.0,147.69600,291.32300
4,NM_000018.4,3853.260000,5505.7000,2998.97000,3269.560000,1915.14000,6124.94000,5311.2200,4817.64000,3997.79000,...,8474.290000,1986.51000,2062.04000,6458.4100,2830.43000,5175.77000,2632.81000,0.0,1836.96000,4345.36000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78746,NR_170930.1,0.000000,0.0000,0.00000,0.000000,0.00000,0.00000,16.9050,0.00000,46.89300,...,77.327200,21.21770,30.06150,84.6140,32.94070,0.00000,0.00000,0.0,0.00000,0.00000
78747,NR_170931.1,0.167116,0.0000,24.03430,55.899300,3.80102,23.02010,0.0000,6.97707,1.02534,...,0.012251,3.41303,0.00000,62.8400,0.06845,8.14061,0.00000,0.0,16.39390,7.70551
78748,NR_170932.1,71.403100,99.5886,30.20180,38.249200,28.99370,70.00940,73.7652,105.84800,106.53600,...,108.979000,43.69110,41.53030,148.1830,38.38150,75.81180,42.89750,0.0,19.43150,79.12870
78749,NR_170933.1,8.122410,41.3945,6.67573,17.916100,6.60821,5.92063,20.5814,20.10450,12.89330,...,36.739600,21.92300,7.84653,36.5171,13.90870,14.68530,9.65578,0.0,2.22746,33.07580
78750,NR_170934.1,2.505970,11.5898,0.00000,0.000023,5.18731,0.00000,0.0000,0.00000,0.00000,...,0.000000,0.00000,0.00000,0.0000,0.00000,0.00000,0.00000,0.0,7.72891,0.00000